services:
  kexa:
    build: https://github.com/kexa-io/Kexa.git
    #image: innovtech/kexa
    env_file:
      - .env
    volumes:
      - ~/.kube/config:/usr/src/config
      - ./config:/usr/src/app/config
      - ./rules:/usr/src/app/rules
    networks:
      - bbdnet
  bdd:
    image: postgres:latest
    container_name: bdd
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admn45
      POSTGRES_DB: kexabdd
      PGDATA: /var/lib/postgresql/data/pgdata # Emplacement des données à l'intérieur du conteneur
    volumes:
      - ./bdd:/var/lib/postgresql/data
    networks:
      - bbdnet
networks:
  bbdnet: