services:
  kexa:
    build: https://github.com/kexa-io/Kexa.git
    #image: innovtech/kexa
    container_name: kexa
    env_file:
      - .env
    environment:
      - DEBUG_LEVEL=TRACE
    volumes:
      - ~/.kube/config:/usr/src/config
      - ./config:/usr/src/app/config
      - ./rules:/usr/src/app/rules
    depends_on:
     - bddpostgresql

  bddpostgresql:
    image: postgres:latest
    container_name: bddpostgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admn45
      POSTGRES_DB: kexabdd
      PGDATA: /var/lib/postgresql/data/pgdata # Emplacement des données à l'intérieur du conteneur
    volumes:
      - ./bddpostgresql:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admn45
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - bddpostgresql

